## declare GitLab job templates
include:
  # declares the defaults
  - local: "ci/default.yml"
  # jobs from GitLab that can be extended/overwritten
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  ## declare the jobs
  - local: "ci/jobs.yml"
